### ISSUE TITLE
Natlan Font

### ISSUE THREAD

**Issue by fontsshin** [SpeedyOrc-C/HoYo-Glyphs#19]
PLEASEEE add the Natlan Script 🙏🙏🔥🔥
thank you so much <3

**Comment by SpeedyOrc-C** [comment]
Actually, I haven’t seen any written text in Natlan, but only the Khænri’ah script.

**Comment by SpeedyOrc-C** [comment]
@Etymodes just told me that Natlan uses a slightly modified Teyvat script, so they don't have their own writing system. This is similar to two different fonts for English.

Penacony's script is also very similar to the one you see in the Herta Space Station. That's why we don't have it in this repo neither.

**Comment by fontsshin** [comment]
ohh, thank you! The script on the stone tablet is khaenri'ahn?
